version: '3'
services:
   appx:
    build: ./appx
    # command: bash  -c "dotnet ef database update"
    #volumes:
    #   - .:/myapp
    ports:
      - "8081:8081"    
    networks:
      default:
      external:
        name: nat